### PR TITLE
Update Sources.txt for my songs.

### PR DESCRIPTION
**Pull request by MeepManToy**
I'm relatively new to Clone Hero, and my charts aren't perfect, but I hope some people like them! Enjoy!

### CODE REVIEW

**Comment by Paturages** [comment]
[You might wanna have a look at charting basics before going further](https://www.youtube.com/playlist?list=PL3sq4ji1jUT0z2AfwSgVpdItr6FtUaNr5)

**Comment by MeepManToy** [comment]
Alright. Like I said I'm no expert on charting, just figured it'd be good to get me some exposure. I'm trying to practice as much as possible, and I can't get used to Moonscraper. I can only use Feedback.

**Comment by MeepManToy** [comment]
Like I have moonscraper installed, I just find Feedback to be easier.

**Comment by Paturages** [comment]
Doesn't have to do anything with choice of software, just check "Tempo Mapping & Syncing" for a start

**Comment by MeepManToy** [comment]
Alright, thanks.

**Pull request closed without merging**
