### PR TITLE
Update sources.txt

### PR DESCRIPTION
**Pull request by topstring**
topstring's charts :: https://drive.google.com/drive/folders/1ert7uoJZBI5JZZWc9JirGfFQzwp53tch?usp=sharing

### CODE REVIEW

**Comment by Paturages** [comment]
Hey, there's quite a bit of room for improvement here. For example, among other issues:
* LANDMVRKS - Fantasy: there's a weird delay, the notes are coming way later than they should be and I don't see any delay information anywhere. In any case, the delay should be charted inside your chart (i.e. in your tempo map)
* LANDMVRKS - Fantasy: missing a lot of notes at around 0:49 ("bridge"/"verses" sections)
* Secrets - Last Time: no star power
* Secrets - Last Time: lots of note placement issues, e.g. 0:08.94 should be Y B Y R instead of B Y R G, 0:26.58 should be something like Y R O R instead of Y B O R, 0:28.70 should be B O B Y instead of O B Y R, and so on...

The higher the notes go, the more towards orange they should go. The lower the notes go, the more towards green they should go. These are the basic rules of note placement.

If you're still not sure how your charts can be improved, feel free to bring your charts to #charting-feedback on the CH Discord and/or to the [New Charter Support Discord](https://discord.gg/eZpZ4xX) where we'll be able to help you more on improving your charts.

**Comment by Duknine2** [comment]
hey Paturages, i need to talk to you, i got many questions but i don't know where ask

**Comment by Paturages** [comment]
@Duknine2 just DM me on Discord (Paturages#9405)

**Comment by Paturages** [comment]
Closing inactive PRs

**Comment by topstring** [comment]
Hey mate apologies for such a delay in my response, I’ve been super busy with work. 

In your opinion where there songs worthy of being submitted? If that means taking down the ones that need improvement I’d be happy to do so and then re- submit what’s left?

That way I can work on re doing lesser quality charts in spare time

Thanks - Topstring

**Comment by Paturages** [comment]
As advised, I think it's important that you at least know what makes a chart good and acceptable before you keep going (and potentially waste more time) because the mistakes I pointed out are recurrent and you're bound to keep doing them on subsequent charts before you figure out how you can fix them, and more importantly *why* you should fix them. I also happen to be super busy with work, so I'm sorry I can't help you much more than what I've posted here before.

**Comment by topstring** [comment]
That’s all good man I’ll take your advice and work on it when I can, hopefully one day I can get there haha

**Pull request closed without merging**
